server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    types {
        application/manifest+json  webmanifest;
    }

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        expires 0;
    }

    location = /site.webmanifest {
        add_header Cache-Control "no-cache";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
